config/routes.rb
Wilfred::Application.routes.draw do
  resources :session_items

  resources :sessions

  resources :items

end

app/models/session_item.rb
class SessionItem < ActiveRecord::Base
	belongs_to :item
	belongs_to :session

	def default_session_qty
    	read_attribute(:session_qty).presence ||= 0
  	end

	validates_presence_of :item_id
	validates :item_id, uniqueness: true
	validates_presence_of :session_id
end

app/controllers/session_items_controller.rb
class SessionItemsController < ApplicationController
  before_action :set_session_item, only: [:show, :edit, :update, :destroy]
  


  # GET /session_items
  # GET /session_items.json
  def index
    @session_items = SessionItem.all
  end

  # GET /session_items/1
  # GET /session_items/1.json
  def show
  end

  # GET /session_items/new
  def new
    @session_item = SessionItem.new
  end

  # GET /session_items/1/edit
  def edit
  end

  # POST /session_items
  # POST /session_items.json
  def create
    @session_item = SessionItem.new(session_item_params)
    respond_to do |format|
      if @session_item.save
        format.html { redirect_to @session_item, notice: 'Session item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @session_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @session_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /session_items/1
  # PATCH/PUT /session_items/1.json
  def update
    respond_to do |format|
      if @session_item.update(session_item_params)
        remove_item_from_inventory
        format.html { redirect_to @session_item, notice: 'Session item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @session_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_item_from_inventory
    @session_item = SessionItem.find(params[:id])
    a = @session_item.item
    a.qty -= @session_item.session_qty
    a.save
  end

  def return_item_to_inventory
    @session_item = SessionItem.find(params[:id])
    a = @session_item.item
    a.qty += @session_item.session_qty
    a.save
  end

  # DELETE /session_items/1
  # DELETE /session_items/1.json
  def destroy
    return_item_to_inventory
    @session_item.destroy
    respond_to do |format|
      format.html { redirect_to session_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_item
      @session_item = SessionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_item_params
      params.require(:session_item).permit(:item_id, :session_id, :session_qty, :note)
    end
end

app/helpers/session_items_helper.rb
module SessionItemsHelper
end

app/views/session_items/_form.html.erb
<%= form_for(@session_item) do |f| %>
  <% if @session_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@session_item.errors.count, "error") %> prohibited this session_item from being saved:</h2>

      <ul>
      <% @session_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="row">
      <div class="large-12 columns field">
        <%= f.label :item_id  %><br>
        <%= f.select(:item_id, Item.order("name").map {|s| [s.name, s.id]}) %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns field">
        <%= f.label :session_id %><br>
        <%= f.select(:session_id, Session.order("id").map {|s| [s.name, s.id]}) %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns field">
        <%= f.label :session_qty %><br>
        <%= f.number_field :session_qty %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns field">
        <%= f.label :note %><br>
        <%= f.text_area :note %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns actions">
        <%= button_tag(type: 'submit' , class: "button") do %>
          Save
        <% end %>
      </div>
    </div>
  </form>
<% end %>

app/views/session_items/edit.html.erb
<h1>Editing Session Item</h1>

<%= render 'form' %>
<div class="row">
	<%= link_to 'Item', @session_item, :class => "button" %>
	<%= link_to 'List of Session Items', session_items_path, :class => "button" %>
</div>

app/views/session_items/index.html.erb
<h1>Listing: Session Items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Session</th>
      <th>QTY</th>
      <th>Note</th>
      <th>Actions</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @session_items.each do |session_item| %>
      <tr>
        <td><%= session_item.item.name %></td>
        <td><%= session_item.session.name %></td>
        <td><%= session_item.session_qty %></td>
        <td><%= session_item.note %></td>
        <td><%= link_to 'Details', session_item %></td>
        <td><%= link_to 'Edit', edit_session_item_path(session_item) %></td>
        <td><%= link_to 'Delete', session_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row">
  <%= link_to 'New Session item', new_session_item_path, :class => 'button' %>
</div>

app/views/session_items/new.html.erb
<h1>New Session Item</h1>

<%= render 'form' %>

<div class="row">
	<%= link_to 'Back', session_items_path, :class => "button" %>
</div>

app/views/session_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @session_item.item.name %>
</p>

<p>
  <strong>Session:</strong>
  <%= @session_item.session.name %>
</p>

<p>
  <strong>Session qty:</strong>
  <%= @session_item.session_qty %>
</p>

<p>
  <strong>Note:</strong>
  <%= @session_item.note %>
</p>

<%= link_to 'Edit', edit_session_item_path(@session_item) %> |
<%= link_to 'Back', session_items_path %>